/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js';
import * as beet from '@metaplex-foundation/beet';
import * as beetSolana from '@metaplex-foundation/beet-solana';
export type MarketInfo = {
  market: web3.PublicKey;
  ordersRootIndex: number;
  traderIndex: number;
  baseBalance: beet.bignum;
  quoteBalance: beet.bignum;
  quoteVolume: beet.bignum;
  /** Bounded cancel-all byte cursor, or u32::MAX after a complete pass. */
  cancelAllScanCursor: number;
  numOpenGlobalOrders: number;
  lastSyncedOrderSequenceNumber: beet.bignum;
};

/**
 * @category userTypes
 * @category generated
 */
export const marketInfoBeet = new beet.BeetArgsStruct<MarketInfo>(
  [
    ['market', beetSolana.publicKey],
    ['ordersRootIndex', beet.u32],
    ['traderIndex', beet.u32],
    ['baseBalance', beet.u64],
    ['quoteBalance', beet.u64],
    ['quoteVolume', beet.u64],
    ['cancelAllScanCursor', beet.u32],
    ['numOpenGlobalOrders', beet.u32],
    ['lastSyncedOrderSequenceNumber', beet.u64],
  ],
  'MarketInfo',
);
