/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet';
import {
  QuoteAtomsPerBaseAtom,
  quoteAtomsPerBaseAtomBeet,
} from '../accounts/QuoteAtomsPerBaseAtom';
import { BaseAtoms, baseAtomsBeet } from '../accounts/BaseAtoms';
import { OrderType, orderTypeBeet } from './OrderType';
/**
 * One placed order inside a BatchUpdateLog: PlaceOrderLog without the market
 * and trader, which are in the header.
 */
export type PlaceOrderLogEntry = {
  price: QuoteAtomsPerBaseAtom;
  baseAtoms: BaseAtoms;
  orderSequenceNumber: beet.bignum;
  orderIndex: number;
  lastValidSlot: number;
  orderType: OrderType;
  isBid: boolean;
  padding: number[]; /* size: 6 */
};

/**
 * @category userTypes
 * @category generated
 */
export const placeOrderLogEntryBeet =
  new beet.BeetArgsStruct<PlaceOrderLogEntry>(
    [
      ['price', quoteAtomsPerBaseAtomBeet],
      ['baseAtoms', baseAtomsBeet],
      ['orderSequenceNumber', beet.u64],
      ['orderIndex', beet.u32],
      ['lastValidSlot', beet.u32],
      ['orderType', orderTypeBeet],
      ['isBid', beet.bool],
      ['padding', beet.uniformFixedSizeArray(beet.u8, 6)],
    ],
    'PlaceOrderLogEntry',
  );
