/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js';
import * as beet from '@metaplex-foundation/beet';
import * as beetSolana from '@metaplex-foundation/beet-solana';

/**
 * Arguments used to create {@link BatchUpdateLog}
 * @category Accounts
 * @category generated
 */
export type BatchUpdateLogArgs = {
  market: web3.PublicKey;
  trader: web3.PublicKey;
  numCancels: number;
  numOrders: number;
};
/**
 * Holds the data for the {@link BatchUpdateLog} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class BatchUpdateLog implements BatchUpdateLogArgs {
  private constructor(
    readonly market: web3.PublicKey,
    readonly trader: web3.PublicKey,
    readonly numCancels: number,
    readonly numOrders: number,
  ) {}

  /**
   * Creates a {@link BatchUpdateLog} instance from the provided args.
   */
  static fromArgs(args: BatchUpdateLogArgs) {
    return new BatchUpdateLog(
      args.market,
      args.trader,
      args.numCancels,
      args.numOrders,
    );
  }

  /**
   * Deserializes the {@link BatchUpdateLog} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0,
  ): [BatchUpdateLog, number] {
    return BatchUpdateLog.deserialize(accountInfo.data, offset);
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link BatchUpdateLog} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig,
  ): Promise<BatchUpdateLog> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig,
    );
    if (accountInfo == null) {
      throw new Error(`Unable to find BatchUpdateLog account at ${address}`);
    }
    return BatchUpdateLog.fromAccountInfo(accountInfo, 0)[0];
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'MNFSTqtC93rEfYHB6hF82sKdZpUDFWkViLByLd1k1Ms',
    ),
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, batchUpdateLogBeet);
  }

  /**
   * Deserializes the {@link BatchUpdateLog} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [BatchUpdateLog, number] {
    return batchUpdateLogBeet.deserialize(buf, offset);
  }

  /**
   * Serializes the {@link BatchUpdateLog} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return batchUpdateLogBeet.serialize(this);
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link BatchUpdateLog}
   */
  static get byteSize() {
    return batchUpdateLogBeet.byteSize;
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link BatchUpdateLog} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment,
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      BatchUpdateLog.byteSize,
      commitment,
    );
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link BatchUpdateLog} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === BatchUpdateLog.byteSize;
  }

  /**
   * Returns a readable version of {@link BatchUpdateLog} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      market: this.market.toBase58(),
      trader: this.trader.toBase58(),
      numCancels: this.numCancels,
      numOrders: this.numOrders,
    };
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const batchUpdateLogBeet = new beet.BeetStruct<
  BatchUpdateLog,
  BatchUpdateLogArgs
>(
  [
    ['market', beetSolana.publicKey],
    ['trader', beetSolana.publicKey],
    ['numCancels', beet.u32],
    ['numOrders', beet.u32],
  ],
  BatchUpdateLog.fromArgs,
  'BatchUpdateLog',
);
