/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet';
import * as web3 from '@solana/web3.js';

/**
 * @category Instructions
 * @category Defrag
 * @category generated
 */
export const DefragStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number;
}>([['instructionDiscriminator', beet.u8]], 'DefragInstructionArgs');
/**
 * Accounts required by the _Defrag_ instruction
 *
 * @property [_writable_, **signer**] collector
 * @property [_writable_] market
 * @property [_writable_] baseVault
 * @property [_writable_] quoteVault
 * @property [] baseTokenProgram
 * @property [] quoteTokenProgram
 * @category Instructions
 * @category Defrag
 * @category generated
 */
export type DefragInstructionAccounts = {
  collector: web3.PublicKey;
  market: web3.PublicKey;
  baseVault: web3.PublicKey;
  quoteVault: web3.PublicKey;
  baseTokenProgram: web3.PublicKey;
  quoteTokenProgram: web3.PublicKey;
  systemProgram?: web3.PublicKey;
};

export const defragInstructionDiscriminator = 14;

/**
 * Creates a _Defrag_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category Defrag
 * @category generated
 */
export function createDefragInstruction(
  accounts: DefragInstructionAccounts,
  programId = new web3.PublicKey('MNFSTqtC93rEfYHB6hF82sKdZpUDFWkViLByLd1k1Ms'),
) {
  const [data] = DefragStruct.serialize({
    instructionDiscriminator: defragInstructionDiscriminator,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.collector,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.market,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.baseVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.quoteVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.baseTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.quoteTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
