name: Benchmark
on:
  push:
    branches: ['main']
    paths:
      [
        'lib/**',
        'programs/**',
      ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: '2.2.20'
  RUST_TOOLCHAIN: '1.86.0'

jobs:
  benchmark:
    name: Benchmark CU
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Checkout benchmarking repo
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          repository: CKS-Systems/manifest-private
          token: ${{ secrets.MANIFEST_PAT }}
          path: manifest-private
          submodules: recursive
          persist-credentials: false

      - name: Switch submodule to current HEAD
        run: cd $GITHUB_WORKSPACE/manifest-private/deps/manifest; git fetch origin $GITHUB_SHA; git checkout $GITHUB_SHA

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.9'

      - name: Cache dependencies
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          shared-key: "solana-${{ env.SOLANA_VERSION }}"

      - name: Set Rust version
        run: rustup toolchain install ${{ env.RUST_TOOLCHAIN }}

      - name: Install Solana
        run: |
          curl --fail --silent --show-error --location --proto '=https' --tlsv1.2 \
            --output solana-install.sh https://release.anza.xyz/v${{ env.SOLANA_VERSION }}/install
          echo '4caed81545b20ddcbc06d65ca8ef8dc69fc9e68fe93a868f5b508309021b49af  solana-install.sh' | sha256sum --check --strict
          sh solana-install.sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana --version
          echo "Generating keypair..."
          solana-keygen new -o "$HOME/.config/solana/id.json" --no-passphrase --silent

      - run: rustup toolchain update nightly && rustup default nightly

      - name: Run benchmark
        run: cd $GITHUB_WORKSPACE/manifest-private; ./benchmarking/benchmark.sh

      - name: Move benchmark results
        run: |
          mv $GITHUB_WORKSPACE/manifest-private/output.txt $GITHUB_WORKSPACE/output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@86d8bcf4dc945c81ee3547d15499abafc89a57b5 # HEAD at review time
        with:
          name: CU Benchmark
          tool: 'customSmallerIsBetter'
          output-file-path: output.txt
          fail-on-alert: true
          summary-always: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true

          # Push and deploy GitHub pages branch automatically
          auto-push: true
